### ISSUE TITLE
Pip install failed (solved partically).

### ISSUE THREAD

**Issue by EvilOlaf** [gissehel/megacl#1]
Just tried to install megacl with pip on Debian 7. Installed packages are python-pip and build-essential.

http://pastebin.com/CSvfhtAm

Best regards
Olaf

Ok already solved: package python2.7-dev also needed to successfully build pycrypto.
Furthermore an installation without root privileges doesn't work. 
So installation was successfull, but it won't start:

```
Traceback (most recent call last):
  File "/usr/local/bin/mcl", line 4, in <module>
    from megacllib import MegaCommandLineClient
  File "/usr/local/lib/python2.7/dist-packages/megacllib/__init__.py", line 1, in <module>
    from .commandline import MegaCommandLineClient
  File "/usr/local/lib/python2.7/dist-packages/megacllib/commandline.py", line 7, in <module>
    import yaml
ImportError: No module named yaml
```

So pip did not solve this dependency and I had to install python-yaml manually and now it works.

On Debian6 install run into an error I couldn't solve yet.
http://pastebin.com/aNB3LWbz

**Comment by gissehel** [comment]
_megacl_ use sevrals dependencies, most of them are pure python packages, so pip handle them quite well.

pycrypto is special because it need to compile C code in order, so pip only works if "everything is ready to compile", which means under linux distribution having all packages like "gcc" and such (and under windows having visual studio 2008).

Thus, I would recommend to install pycrypto under linux as a distribution package and not with pip (I just searched, it look like the name of pycrypto under debian is the same than under ubuntu, that is `python-crypto`).

So typing

```
sudo apt-get install python-crypto
```

before lauching `sudo pip install megacl` should be enougth.

---

Concerning the `yaml`, indeed, I didn't specified as a dependency, but I didn't really wanted it as a dependency, I only used it to debug code, so I just removed the `import yaml` (and released a 0.4.5), that should not cause problem anymore elsewhere.

---

Concerning the _Debian 6_ problem, I don't understand what is happening here. It look like mcl is not found within the archive, while it really exists... Perhaps pip on Debian 6 has a problem with mcl being a symbolic link, I don't know....

**Comment by EvilOlaf** [comment]
As written pip does the installation of pycrypto well if python2.7-dev and build-essential packages are installed. So there is no need to install it by the package manager :-).

Got an idea.
richardasaurus / mega.py uses python2.7 
Unfortunately Debian 6 contains python2.6 only. So maybe we've got the incompatibility here.

Olaf

**Comment by gissehel** [comment]
I have a "synology nas" as hardware, with a "optware" linux distribution on top of the standard synology firmware (so highly "not a mainstream distribution") and it's still stuck with python 2.6.

There is no problem with using pip to install megacl on in.

**Comment by gissehel** [comment]
If I can find few GB to remove on my HD, I'll try to see if I can install a debian 6 on virtual box

**Comment by EvilOlaf** [comment]
Less than 2GB would be enough ;)

Olaf
